### ISSUE TITLE
Running the demo on camera feed

### ISSUE THREAD

**Issue by sandyflute** [open-mmlab/mmskeleton#110]
Hi @yjxiong @yysijie , is there a way to run this quickly on camera feed ?

Thanks.

**Comment by intvo** [comment]
did you find a way to run it on using the camera? 
Please let me know

**Comment by yysijie** [comment]
@sandyflute, @intvo 
Hi, the speed of prediction is enough fast. However, this implementation extracts all the skeleton sequence from video by Openpose offline, then predicts the action type according to the skeleton sequences. Thus, if you want to run this framework in real time, you should modify the code. you should run the Openpose in real time, and predict the action type according to the latest 20~30 frames at the same time. Welcome to create a pull request if you implement this feature.

**Comment by lianuo** [comment]
@yysijie 
in the demo.py
data is fed in to the model.but the size is (3,222,18,2)
3 means 3 chanel
222 means the lenth of video,222 frames
18 is the keypoints 
2 is the person number

output, feature = self.model.extract_feature(data)

the output size is 1,400,56,18,2

I have two questions 
1. the data size should be if I want to predict action in realtime
2.in the output size, what the 56 means?

Thanks~

**Comment by yjxiong** [comment]
@lianuo 
this sounds like a very good idea. Do you plan to releaes the code realtime demo?

**Comment by liuk3615** [comment]
Would you like to know the implementation of real-time details。 Is it convenient to send it to the mailbox？Thanks very much@lianuo

**Comment by durianno1** [comment]
> it may be a litte complex, if there are many person in the video ,it is nessery to add pose tracking method to predict every ones action.

I used other openpose projects to extract 18 key points from each frame of the video.but how can i modify these data ,and put them into the action recognition demo.

**Comment by durianno1** [comment]
> @sandyflute, @intvo
> Hi, the speed of prediction is enough fast. However, this implementation extracts all the skeleton sequence from video by Openpose offline, then predicts the action type according to the skeleton sequences. Thus, if you want to run this framework in real time, you should modify the code. you should run the Openpose in real time, and predict the action type according to the latest 20~30 frames at the same time. Welcome to create a pull request if you implement this feature.

I used other openpose projects to extract 18 key points from each frame of the video.but how can i modify these data ,and put them into the action recognition demo.thank u

**Comment by zjzhengyin** [comment]
> 它有效，我只是将姿势打包为（3，t，18,1）并将其输入网络。
> t是时间，正如你的建议，我把它设置为20. 
> 现在它可以实时工作。
Hello, could you send me this code for me to learn?

**Comment by zz-ycx** [comment]
> @yysijie
> in the demo.py
> data is fed in to the model.but the size is (3,222,18,2)
> 3 means 3 chanel
> 222 means the lenth of video,222 frames
> 18 is the keypoints
> 2 is the person number
> 
> output, feature = self.model.extract_feature(data)
> 
> the output size is 1,400,56,18,2
> 
> I have two questions
> 
> 1. the data size should be if I want to predict action in realtime
>    2.in the output size, how the 56 means,I know it is from 222->111->55.5->56?
>    is this means for every 4 frames we have a prediction of action?
>    Thanks~

hello, i want to konw in st_gcn.py the fourth parameter  1 in the front two  network layer it can be changed by myself.   `st_gcn(in_channels, 64, kernel_size, 1 , residual=False, **kwargs),
            # st_gcn(64, 64, kernel_size, 1, **kwargs),`what this parameter really mean and how does this parameter affect the overall performance?

**Comment by AndyTaiwan** [comment]
@lianuo Could you tell me **how to solve the input video stream problem** that I want to implement the real-time system? Specifically,  VideoCapture() has been used in openpose project to estimate pose, so I can't use that function to get the real-time video stream in the st-gcn project for visualization. For example, I can neither print the st-gcn final weight of each joint nor the predict action at each frame, if the video stream unavailable in st-gcn. Is it possible to get the video stream in both openpose estimation and st-gcn visualization?

**Comment by yjxiong** [comment]
@AndyTaiwan I would say you write a wrapper that handles video capture and call openpose and st-gcn's APIs sequentially. Then the visualization can be done in the wrapper.

**Comment by AndyTaiwan** [comment]
@yjxiong Thanks for your reply! About the wrapper, it is necessary for calling both pose estimation and action recognition APIs to use torch.multiprocessing right? The reason is that the real-time of action recognition need to run openpose and st-gcn at every 20 frames. Please correct me if I am wrong.

**Comment by yjxiong** [comment]
Real-time or not mostly depends on how fast the pose estimation runs on your devices. The wrapper would just grab the frames and send them to OpenPose and ST-GCN. You can implement it in the way you like.

**Comment by csuzenith** [comment]
@lianuo Could you help me if I want to feed the video to is demo for using real time camera~

**Comment by CompliceU** [comment]
Hello, don't know if you have completed the task of this change. @csuzenith @lianuo

**Comment by sonderLIN** [comment]
> It works , I just pack the poses as (3,t,18,1) and feed it in to the network.
> t is the time ,as you suggest,  I set it to be 20.
> Now it can works in realtime.
I retrained the model with my own data. top1 is 88%
But when i run it on camera feed.  The results are terrible.  I pack the poses as (3,30,18,1)
 I don't know what the problem is.  Can you give me some suggestions ?  Thank you!

**Comment by sandyflute** [comment]
Hello,
Sorry guys, i stopped following this thread. I was able to do real time demo with camera without doing any change in the network architecture. If anyone needs help with this immediately, i might be able to guide.

**Comment by xiehaizheng** [comment]
@lianuo  Could you help me if I want to feed the video to is demo for using real time camera~

It works , I just pack the poses as (3,t,18,1) and feed it in to the network.t is the time ,as you suggest, I set it to be 20.Now it can works in realtime.
--

**Comment by xiehaizheng** [comment]
@lianuo  Could you help me if I want to feed the video to is demo for using real time camera~

It works , I just pack the poses as (3,t,18,1) and feed it in to the network.t is the time ,as you suggest, I set it to be 20.Now it can works in realtime.
--

**Comment by xiehaizheng** [comment]
Hello, don't know if you have completed the task of this change. @csuzenith @yysijie @yjxiong @durianno1
