### ISSUE TITLE
How to get an immovable result?

### ISSUE THREAD

**Issue by RayLeijingsi** [open-mmlab/mmskeleton#229]
### Dataset used
own dataset
### Question
I would get many different values of top1 when i training myself model using own dataset, which only has two classes. sometimes geting 82%, sometimes geting 70%... I try to use random.seed() to make it, but it was insuccess. 
How to solve it?

**Comment by SensyJiang** [comment]
@RayLeijingsi Same problem.Have you solved it? It will be so kind if you could share your solution.

**Comment by RayLeijingsi** [comment]
> @RayLeijingsi Same problem.Have you solved it? It will be so kind if you could share your solution.

yes. Inspiration from the Internet， I tried to increase the training of epoch and add data. Instability due to lack of data. you can try this two methods.
