### ISSUE TITLE
problem about training on my own dataset

### ISSUE THREAD

**Issue by Angel113110** [open-mmlab/mmskeleton#231]
### Code version (Git Hash) and PyTorch version
    pytorch 1.1.0
### Dataset used
    own raw student dataset
### Other comments
    Hi, author. I have a question for you. I have dataset which is consist of students videos. I can extract their keypoints information by using openpose. The labels I use maybe different from yours.  I want to know how to do for processing my dataset and training on st-gcn model. I need to manually generate labels for my dataset, right?

**Comment by yysijie** [comment]
@Angel113110 
Hi, now we support custom dataset, please update mmskeleton and refer to https://github.com/yysijie/mmskeleton-private/blob/master/doc/CUSTOM_DATASET.md

**Comment by zhipengding1** [comment]
Hello, this webpage is invalid, can you please upload it again?
