### ISSUE TITLE
If you want to formulate ConvTemporalGraphical in an equation, how would you do it?

### ISSUE THREAD

**Issue by abduallahmohamed** [open-mmlab/mmskeleton#232]
Hi, 

This is a generic understanding question. I'm trying to map the code with the repo but I have hard time formulating the ConvTemporalGraphical model to match what is inside the paper, can you help regards this?

Thanks

**Comment by yjxiong** [comment]
It's implemented exactly as described in Eq. 10 in the paper. Let me know if you have other question.

**Comment by abduallahmohamed** [comment]
Thanks for the quick reply, what I don't quite get is, why to: 
`        x = x.view(n, self.kernel_size, kc//self.kernel_size, t, v)`

int the forward function?

```
 def forward(self, x, A):
        assert A.size(0) == self.kernel_size

        x = self.conv(x) 
       #x Shape is (batch,out_channels * kernel_size,time steps, features)
        n, kc, t, v = x.size()
        x = x.view(n, self.kernel_size, kc//self.kernel_size, t, v)
       #x Shape is (batch,kernel_size,out_channels ,time steps, features)
        x = torch.einsum('nkctv,kvw->nctw', (x, A))

        return x.contiguous(), A
```

**Comment by yjxiong** [comment]
See the comments in code. 

here is the `einsum` explanation. 

https://pytorch.org/docs/stable/torch.html#torch.einsum

It does the aggregation of all partition subsets after the linear transform. You can write down the formula and verify it.
