### ISSUE TITLE
How to convert .pt model to .onnx model

### ISSUE THREAD

**Issue by qualia0000** [open-mmlab/mmskeleton#239]
Similar problem on converting .pt model to .onnx model. After loading the .pt model, I executed:
`example = torch.ones(3, 1, 18, 1)`
`example = example.unsqueeze(0)`
`example = example.float().to(device).detach()`
`torch.onnx.export(model, example, "onnx_model_80.onnx")`
Then I got following error:
`File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\__init__.py", line 25, in export return utils.export(*args, **kwargs) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 131, in export strip_doc_string=strip_doc_string) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 363, in _export _retain_param_name, do_constant_folding) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 278, in _model_to_graph _disable_torch_constant_prop=_disable_torch_constant_prop) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 188, in _optimize_graph graph = torch._C._jit_pass_onnx(graph, operator_export_type) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\__init__.py", line 50, in _run_symbolic_function return utils._run_symbolic_function(*args, **kwargs) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 602, in _run_symbolic_function n.kindOf("value"))) RuntimeError: Unsupported prim::Constant kind:s. Send a bug report.`
I am aware that the function `torch.onnx.export` should contain params called `input_names` and `output_names` but I got difficulty acquring them in the net as I used `model.state_dict()` to list the whole net's params.
Could you give any advise on it? Thank you.

**Comment by qualia0000** [comment]
After debugging I found that the `torch.einsum` triggered the error. It is not of supported operators according to https://pytorch.org/docs/1.1.0/onnx.html?highlight=onnx#module-torch.onnx.

**Comment by XinyingZheng** [comment]
> Similar problem on converting .pt model to .onnx model. After loading the .pt model, I executed:
> `example = torch.ones(3, 1, 18, 1)`
> `example = example.unsqueeze(0)`
> `example = example.float().to(device).detach()`
> `torch.onnx.export(model, example, "onnx_model_80.onnx")`
> Then I got following error:
> `File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\__init__.py", line 25, in export return utils.export(*args, **kwargs) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 131, in export strip_doc_string=strip_doc_string) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 363, in _export _retain_param_name, do_constant_folding) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 278, in _model_to_graph _disable_torch_constant_prop=_disable_torch_constant_prop) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 188, in _optimize_graph graph = torch._C._jit_pass_onnx(graph, operator_export_type) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\__init__.py", line 50, in _run_symbolic_function return utils._run_symbolic_function(*args, **kwargs) File "D:\ProgramData\Miniconda3\lib\site-packages\torch\onnx\utils.py", line 602, in _run_symbolic_function n.kindOf("value"))) RuntimeError: Unsupported prim::Constant kind:s. Send a bug report.`
> I am aware that the function `torch.onnx.export` should contain params called `input_names` and `output_names` but I got difficulty acquring them in the net as I used `model.state_dict()` to list the whole net's params.
> Could you give any advise on it? Thank you.

I also encountered this problem, have you finally solved this problem？Looking forward to your reply，thank you

**Comment by zhanghaowei01** [comment]
我也遇到了这个问题，您终于解决了这个问题吗？期待您的答复，谢谢

**Comment by zhanghaowei01** [comment]
I also encountered this problem, have you finally solved this problem？Looking forward to your reply，thank you

**Comment by qualia0000** [comment]
@zhanghaowei01 Sorry I didn't use the .onnx model eventually but I saw that PyTorch 1.7 supports the `torch.einsum` operator on   .onnx model generating. Maybe this could help.

**Comment by henbucuoshanghai** [comment]
@zhanghaowei01    have you solve it ?how?
