### ISSUE TITLE
pose_demo does not exist

### ISSUE THREAD

**Issue by suarezyan** [open-mmlab/mmskeleton#242]
Hello, thanks for sharing your awesome project:
when I want to verify that mmskeleton installed correctly,use:
mmskl pose_demo
some errors occur:

File "/usr/local/bin/mmskl", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mmskeleton/tools/mmskl", line 71, in <module>
    main()
  File "/mmskeleton/tools/mmskl", line 66, in main
    cfg = parse_cfg()
  File "/mmskeleton/tools/mmskl", line 38, in parse_cfg
    cfg = Config.fromfile(sys.argv[1])
  File "/usr/local/lib/python3.6/site-packages/mmcv-0.2.13-py3.6-linux-x86_64.egg/mmcv/utils/config.py", line 78, in fromfile
    check_file_exist(filename)
  File "/usr/local/lib/python3.6/site-packages/mmcv-0.2.13-py3.6-linux-x86_64.egg/mmcv/utils/path.py", line 32, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/mmskeleton/pose_demo" does not exist

Is pose_demo the same as demo?
I look forward to thanking you for your reply

**Comment by YZYLHR** [comment]
Same question . Do you know how to deal with it?

**Comment by yysijie** [comment]
@YZYLHR @suarezyan 
Hi, please try to run this command under the root path of mmskeleton

**Comment by YZYLHR** [comment]
Dear Sir/Madam,


I have another question. When I test my dataset,how much show the window_size should be set ? Is it the same as training ?&nbsp; In test.yaml ,&nbsp;the default value is -1. Maybe I should change it, right ?
Looking forward to your reply.


Best Regards,
Zhaoyang You.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sijie yan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月7日(星期一) 晚上7:33
收件人:&nbsp;"open-mmlab/mmskeleton"<mmskeleton@noreply.github.com&gt;;
抄送:&nbsp;"小仙女"<1161360870@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmskeleton] pose_demo does not exist (#242)




Closed #242.
