### ISSUE TITLE
from openpose import pyopenpose as op

### ISSUE THREAD

**Issue by luoluo-gif** [open-mmlab/mmskeleton#248]
How to achieve this“from openpose import pyopenpose as op”？
I'm a beginner and I hope to get some your advice on installing Pyopenpose.

**Comment by yysijie** [comment]
Hi, please refer to https://github.com/CMU-Perceptual-Computing-Lab/openpose#installation-reinstallation-and-uninstallation.

**Comment by gt5-gerry** [comment]
Any idea how I can open this: https://github.com/chonyy/basketball-shot-detection ?
