### ISSUE TITLE
Kinetics- skeleton 

### ISSUE THREAD

**Issue by luoluo-gif** [open-mmlab/mmskeleton#267]
![image](https://user-images.githubusercontent.com/54338956/69523186-2ea47280-0f9e-11ea-9a7c-fe08ae2177f8.png)

**Is the accuracy of the 'kinetic skeleton' dataset only 31.6%? Is this too low? How to improve its accuracy?** @yysijie

**Comment by yjxiong** [comment]
This is using only the skeleton locations for recognition, without looking at the RGB information. There is discussion about the accuracy in the ST-GCN paper. Please refer to the paper for more information.

**Comment by dusa2** [comment]
@yjxiong Do you have the two-stream model you used for the experiments in the paper available?
