### ISSUE TITLE
Multiple skeletons in the video

### ISSUE THREAD

**Issue by dusa2** [open-mmlab/mmskeleton#275]
For multiple skeletons in the video, how does the spatitemporal graphs are constructed? Are the two skeletons linked together? In my dataset, there are always two skeletons and how they interact and how they move together is very important to recognize the action. I wonder how these two skeletons are reprsented by graphs? and whether they are linked? If not, are their features summed for the frame?

**Comment by yysijie** [comment]
@dusa2,
In our implementation, we simply sum all representations of skeletons together.
