### ISSUE TITLE
What's the meaning of N,C,T,V,M?

### ISSUE THREAD

**Issue by cehanluo** [open-mmlab/mmskeleton#277]
Hi. I am trying to custom the dataset and looking at related codes.

The data feeder function (feeder.py) has a requirement for input data, which should have a shape of (N, C, T, V, M). Could I know what the meanings are of those parameters?

As far as I guess, 
N: the number of samples. 
C: the number of coordinates? e.g. (x,y,z), where z is z coordinate or visibility or scores?
T: the number of max_frame e.g. 300 as the default?
V:  the number of joints used in the experiments?
M: the number of max body? 

Am I correct?

Thanks.

**Comment by dusa2** [comment]
N: the number of samples in your batch (video clips)
C: channels, for 2D skeletons data this is the coordinates plus the probability of joints (you can check the json files and the openpose format for more information)

others are correct, as far as I am concerned.

**Comment by yysijie** [comment]
@dusa2,
Thanks, you are right.
