### ISSUE TITLE
Dense connections

### ISSUE THREAD

**Issue by dusa2** [open-mmlab/mmskeleton#287]
Not an issue (just discussion) I am checking the paper, and I just wanted to double check: I want to use dense graphs because my skeletons have few joints and this is -I think- one of the reasons I am not getting a good performance, although on the other hand parent child relationship might suffer if I have dense connections.  My understanding is that this wouldn't be a problem in theory, though I will need fixed adjacency defined. Is there anything that goes against the math? To say, connect two hands of a human body?

**Comment by yysijie** [comment]
A property of "convolution" is that the identities of nodes or pixels are not distinguished.
That is to say, the kernel for "neck" and "shoulder" are the same.
The graph structure is a useful clue for perceiving the identity or location.  However, in a symmetrical graph, for example, a complete graph, this clue is lost again. 

So, I do not suggest to use a dense graph.
