### ISSUE TITLE
installation issue (unknown file type '.pyx') 

### ISSUE THREAD

**Issue by omersumer** [open-mmlab/mmskeleton#292]
I installed dependencies and when I run setup.py script (python setup.py develop), I got the following error:

(Cython is installed. In Python 3.7.6, I use with/without creating an environment, the error is the same.)

```
miniconda3/lib/python3.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.7.rc1+ecaf5db' to '0.7rc1+ecaf5db'
  normalized_version,
running develop
running egg_info
writing mmskeleton.egg-info/PKG-INFO
writing dependency_links to mmskeleton.egg-info/dependency_links.txt
writing requirements to mmskeleton.egg-info/requires.txt
writing top-level names to mmskeleton.egg-info/top_level.txt
reading manifest file 'mmskeleton.egg-info/SOURCES.txt'
writing manifest file 'mmskeleton.egg-info/SOURCES.txt'
running build_ext
building 'mmskeleton.ops.nms.gpu_nms' extension
error: unknown file type '.pyx' (from 'mmskeleton/ops/nms/gpu_nms.pyx')
```

**Comment by junhao1999** [comment]
+1

**Comment by jmartinezot** [comment]
+1

**Comment by mathpopo** [comment]
+1

**Comment by mejdidallel** [comment]
+1

**Comment by NingMa-AI** [comment]
+1

**Comment by enjoykcc456** [comment]
+1

**Comment by ferisetiawan** [comment]
+1

**Comment by wind-cludy** [comment]
+1

**Comment by wind-cludy** [comment]
I solved this problem by under step:
```
 cd mmskeleton/ops/nms/
 python setup_linux.py build
```
build folder is created. 
copy build/temp.linux..../*.o to $mmskeleton_home/build/temp.linux.../mmskeleton/ops/nms/
copy build/lib.linux..../*.so to $mmskeleton_home/build/lib.linux.../mmskeleton/ops/nms/*

`cd $mmskeleton_home`
execute 
` python setup.py develop`
again.

**Comment by suzhan-123** [comment]
I encountered the same problem, referring to the method provided by wind-cludy. The problem was not resolved. Still "unknown file type '.pyx'"

**Comment by suzhan-123** [comment]
I found that in the make_cuda_ext method of setup.py they use CUDAextension to process the gpu_nms.pyx file. This caused an error. I don't know if this is a problem with official code.

**Comment by lakshaymehra** [comment]
I am getting the same error even after following the method suggested above.Is there any other way to solve this issue?

**Comment by alishsuper** [comment]
I have the same issue

**Comment by Dongti-tian** [comment]
I solved the problem through  the method provided by wind-cludy. Command lines are as follows:
 cd mmskeleton/ops/nms/
 python setup_linux.py build
![image](https://user-images.githubusercontent.com/59213995/79208170-4bb9df00-7e74-11ea-91cf-628d5de30e34.png)
![image](https://user-images.githubusercontent.com/59213995/79208243-68eead80-7e74-11ea-88f8-56e569eea4df.png)

![image](https://user-images.githubusercontent.com/59213995/79208359-8754a900-7e74-11ea-94b8-76f77db29d98.png)
![image](https://user-images.githubusercontent.com/59213995/79208423-989db580-7e74-11ea-9470-5b83d5641faa.png)
![image](https://user-images.githubusercontent.com/59213995/79208462-a6ebd180-7e74-11ea-9116-f70b21e681e0.png)
python setup.py develop again.

Thanks for wind-cludy's answer

**Comment by xueyingliu** [comment]
I changed python3.5 to python3.7,  this  error disappeared.

**Comment by yysijie** [comment]
Thank you for your help. This bug has been fixed. Please refer to the latest [GETTING_STARTED.md](https://github.com/open-mmlab/mmskeleton/blob/master/doc/GETTING_STARTED.md).
