### ISSUE TITLE
from .cpu_nms import cpu_nms ModuleNotFoundError: No module named 'mmskeleton.ops.nms.cpu_nms'

### ISSUE THREAD

**Issue by li0128** [open-mmlab/mmskeleton#295]
from .cpu_nms import cpu_nms
ModuleNotFoundError: No module named 'mmskeleton.ops.nms.cpu_nms'
How to solve the problem ? Thank you !

**Comment by gregary** [comment]
I got the same error.  And here is my solution.
```
cd mmskeleton/mmskeleton/ops 
make all
```
Then use python setup.py develop to install.

**Comment by yysijie** [comment]
@gregary Thank you for your help.

**Comment by yysijie** [comment]
This bug has been fixed.
