### ISSUE TITLE
Error when loading the model

### ISSUE THREAD

**Issue by ferisetiawan** [open-mmlab/mmskeleton#296]
When I run the testing code

`mmskl configs/recognition/st_gcn_aaai18/kinetics-skeleton/test.yaml --checkpoint ./work_dir/recognition/ST_GCN_18/kinetics-skeleton/epoch_50.pth --gpus 2`

I found this error 

> RuntimeError: don't know how to restore data location of torch.FloatStorage (tagged with gpu)

Do you have any suggestions?
The code is running on my pc with 2 GPUs (RTX2080ti)

Thankyou!

**Comment by ferisetiawan** [comment]
Problem solved.
I did some changes on the `map_location` parameter during the `load_checkpoint`.

**Comment by eng100200** [comment]
@ferisetiawan  what changes you made in map_location?

**Comment by abhi1nandy2** [comment]
> Problem solved.
> I did some changes on the `map_location` parameter during the `load_checkpoint`.

Please show the changes that you made to the map location. Help would be much appreciated 👍

**Comment by Ooo02zzZ** [comment]
> Problem solved.
> I did some changes on the `map_location` parameter during the `load_checkpoint`.
Maybe  this puzzle will be resolved by this blog.
https://www.cnblogs.com/xiaodai0/p/10413711.html

**Comment by RPetitpierre** [comment]
Replacing 'gpu' by 'cuda:0' in load_checkpoint did the trick: `load_checkpoint(model, cfg.load_from, map_location='cuda:0')`
