### ISSUE TITLE
Error : unknown file type '.pyx' everytime I run python setup.py develop On Colab

### ISSUE THREAD

**Issue by lakshaymehra** [open-mmlab/mmskeleton#300]
I have tried the methods suggested in the other issues but they do not work.

I get the following error:

/usr/local/lib/python3.7/site-packages/setuptools/dist.py:453: UserWarning: Normalizing '0.7.rc1+6594153' to '0.7rc1+6594153'
  normalized_version,
running develop
running egg_info
writing mmskeleton.egg-info/PKG-INFO
writing dependency_links to mmskeleton.egg-info/dependency_links.txt
writing requirements to mmskeleton.egg-info/requires.txt
writing top-level names to mmskeleton.egg-info/top_level.txt
reading manifest file 'mmskeleton.egg-info/SOURCES.txt'
writing manifest file 'mmskeleton.egg-info/SOURCES.txt'
running build_ext
building 'mmskeleton.ops.nms.gpu_nms' extension
error: unknown file type '.pyx' (from 'mmskeleton/ops/nms/gpu_nms.pyx')

**Comment by alishsuper** [comment]
I have the same issue

**Comment by MrNN233** [comment]
Have you solved the problem?  I have the same problem.

**Comment by atomtony** [comment]
https://github.com/open-mmlab/mmskeleton/issues/292

**Comment by yysijie** [comment]
Thank you for your help. This bug has been fixed. Please refer to the latest [GETTING_STARTED.md](https://github.com/open-mmlab/mmskeleton/blob/master/doc/GETTING_STARTED.md).
