### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by 1584899550** [open-mmlab/mmskeleton#304]
thanks for your works! 
when I run the command  
mmskl configs/recognition/st_gcn_aaai18/ntu-rgbd-xview/test.yaml
I've got an error
AssertionError: Invalid device id
can you tell me how to solve this problem?
looking for your replay!    thanks a lot.

**Comment by yysijie** [comment]
The default setting uses 4 GPUs. We have modified the default setting in the latest version. So just update the codebase and run the command again:
```
mmskl configs/recognition/st_gcn_aaai18/ntu-rgbd-xview/test.yaml
```
If you want to change the number of gpus, use `--gpus`. For example:
```
mmskl configs/recognition/st_gcn_aaai18/ntu-rgbd-xview/test.yaml --gpus 4
```

**Comment by 1584899550** [comment]
Thank you for your reply. I have solved this problem. Thank you very much!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sijie yan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月24日(星期天) 晚上10:08
收件人:&nbsp;"open-mmlab/mmskeleton"<mmskeleton@noreply.github.com&gt;;
抄送:&nbsp;"我在说"<1584899550@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmskeleton] AssertionError: Invalid device id (#304)





 
The default setting uses 4 GPUs. We have modified the default setting in the latest version. So just update the codebase and run the command again:
 mmskl configs/recognition/st_gcn_aaai18/ntu-rgbd-xview/test.yaml  
If you want to change the number of gpus, use --gpus. For example:
 mmskl configs/recognition/st_gcn_aaai18/ntu-rgbd-xview/test.yaml --gpus 4

**Comment by MaarufB** [comment]
I've got the same error but not for test.yaml, I got that error when running the train.yaml.  This is the command i used ----- mmskl configs/recognition/st_gcn_aaai18/kinetics-skeleton/train.yaml --gpus 4
