### ISSUE TITLE
RuntimeError: Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_batch_norm)

### ISSUE THREAD

**Issue by starry-night-0** [open-mmlab/mmskeleton#305]
When I train my datasets ,and I use the command  

> python main.py recognition -c config/st_gcn/dataset/train.yaml [--work_dir <work folder>]

but I met an error 
> RuntimeError: Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_batch_norm)

How should I do? Could someone help me?

**Comment by XieLinMofromsomewhere** [comment]
请问怎么解决的呢？？

**Comment by starry-night-0** [comment]
> 请问怎么解决的呢？？

我是重新从github下载项目代码并重新配置环境后再运行就没问题了，估计我的问题原因是之前改动过原项目代码导致运行训练有关的程序时报了错，仅供参考~

**Comment by XieLinMofromsomewhere** [comment]
哇靠，重新配置环境真的劝退，我直接覆盖代码得了

**Comment by XieLinMofromsomewhere** [comment]
找到了解决方法，，在recongnition.py的43，44行，`self.model.apply(weights_init).to(self.dev)  #apply()函数将model中的所有的层进行权重初始化
        self.loss = nn.CrossEntropyLoss().to(self.dev) #定义交叉商和损失函数`  
model和loss后面加上'.to(self.dev)'
