### ISSUE TITLE
OSError: CUDA is required to compile MMSkeleton!

### ISSUE THREAD

**Issue by mjk22071998** [open-mmlab/mmskeleton#310]
I have installed CUDA 10.2 . and then installed pytorch, but still I am getting the issue while I run the command

`python setup.py develop`

I get error

`No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2'
Traceback (most recent call last):
  File "setup.py", line 187, in <module>
    include_dirs=[np.get_include()]),
  File "setup.py", line 124, in make_cuda_ext
    raise EnvironmentError('CUDA is required to compile MMSkeleton!')
OSError: CUDA is required to compile MMSkeleton!`

**Comment by trungmanhhuynh** [comment]
@mjk22071998 I encountered the same issues like yours and how I made it worked for my system.

My system has cuda9.0 installed at /usr/local/cuda 

When I installed using the command given in README, by default the newest version of pytorch (1.15.0) and cuda 10.2 will be installed in my private conda enviroments. This caused the issues. 
I guess (I am not sure about this) there is a conflict between my system's cuda and the one supported for pytorch 1.15.0. You can verify this by run '''conda list''' and you will see '''   pytorch:        1.5.0-py3.7_cuda10.2.89_cudnn7.6.5_0 pytorch'''. 

Now, I need to make sure the pytorch I will use supported by system's cuda 9.0. I downgraded pytorch to version 1.0.0, by running '''conda install pytorch=1.0.0 torchvision -c pytorch'''. Then, run '''conda list''' to make sure it appears as '''pytorch:        1.0.0-py3.7_cuda9.0.176_cudnn7.4.1_1 pytorch'''. 

When the cuda versions are consistent ( Again, I guess it is not just cuda, but also gpu driver version), the problem should be resolved. 

Another way I think it will work if you want newer pytorch and cuda 10.0 is updating your GPU driver to the newest version. 

Hope it helps.

**Comment by trungmanhhuynh** [comment]
To be confirmed, updating GPU driver should work.

**Comment by yysijie** [comment]
@trungmanhhuynh, thank you for your update.
@mjk22071998, please choose the correct CUDA version according to the pytorch version, for example:
```
# CUDA 9.2
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=9.2 -c pytorch

# CUDA 10.0
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
```
