### ISSUE TITLE
wrong python mmskl.py pose_demo

### ISSUE THREAD

**Issue by liqier** [open-mmlab/mmskeleton#328]
I have successfully installed mmdet by:

pip install -r requirements/build.txt
pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
pip install -v -e .

However, I got next error when I verify that mmskeleton and mmdetection by "python mmskl.py pose_demo --gpus 1" :
(open-mmlab) zyq@ubuntu:~/mmskeleton$ python mmskl.py pose_demo
/home/zyq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
Load configuration information from ./configs/pose_estimation/pose_demo.yaml

Pose estimation:
INFO:matplotlib.font_manager:Could not open font file /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Could not set the fontsize
INFO:matplotlib.font_manager:generated new fontManager

Bad key "text.kerning_factor" on line 4 in
/home/zyq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "mmskl.py", line 123, in <module>
    main()
  File "mmskl.py", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/home/zyq/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/home/zyq/mmskeleton/mmskeleton/processor/pose_demo.py", line 78, in inference
    model = init_pose_estimator(detection_cfg, estimation_cfg, device=0)
  File "/home/zyq/mmskeleton/mmskeleton/apis/estimation.py", line 20, in init_pose_estimator
    device='cpu')
  File "/home/zyq/mmskeleton/mmdet/mmdet/apis/inference.py", line 33, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/zyq/mmskeleton/mmdet/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zyq/mmskeleton/mmdet/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zyq/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'num_stages'
How can I solve this problem?

**Comment by YeTaoY** [comment]
@liqier  did you slove this problem?

**Comment by zimenglan-sysu-512** [comment]
hi @YeTaoY @liqier 
do u solve this problem? i use the newest mmdetection (v2.1), and meet this problem.

**Comment by happysheep224** [comment]
I met the same problem, how could you fix it?

**Comment by YeTaoY** [comment]
@happysheep224 The problem remains unfixed to me

**Comment by happysheep224** [comment]
have you try conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch

**Comment by YeTaoY** [comment]
@happysheep224 I tried  conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.1 -c pytorch,  and the pytorch version is back to 1.2.0   
but new error occur "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry."

**Comment by happysheep224** [comment]
@YeTaoY yes, that is the error what I meet now

**Comment by liqier** [comment]
> `https://github.com/open-mmlab/mmskeleton/issues/321#issue-628694245

**Comment by CamilleMaurice** [comment]
It was working for me last month, I don't know what changes I've done but I have the same issue. When I roll back to pytorch 1.2.0 I have the following :
pkg_resources.ContextualVersionConflict: (torch 1.2.0 (/home/cmaurice/anaconda3/envs/open-mmlab/lib/python3.7/site-packages), Requirement.parse('torch>=1.3'), {'mmdet'})

**Comment by mytk2012** [comment]
> @happysheep224 I tried conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.1 -c pytorch, and the pytorch version is back to 1.2.0
> but new error occur "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry."

Do you fix it?

**Comment by happysheep224** [comment]
Yeah，rollback the version of mmskeleton to 0.7rc

**Comment by happysheep224** [comment]
or you can modify the  mmskeleton/apis/estimation.py and  mmskeleton/utils/third_party.py, by refer to https://github.com/open-mmlab/mmskeleton/compare/v0.7rc0...v0.7rc1

**Comment by happysheep224** [comment]
I found that the latest mmdet require pytorch &gt;1.3, and the latest mmskeleton require pytorch ==1.2.0, so their requirements are conflict. My solution is roll back the mmdet to 1.2.0, in this version, mmdet require pytorch &gt;=1.1。



杨扬
Yang Yang


&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CamilleMaurice"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 晚上8:29
收件人:&nbsp;"open-mmlab/mmskeleton"<mmskeleton@noreply.github.com&gt;;
抄送:&nbsp;"淼儿"<89255775@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmskeleton] wrong python mmskl.py pose_demo (#328)





 
It was working for me last month, I don't know what changes I've done but I have the same issue. When I roll back to pytorch 1.2.0 I have the following :
 pkg_resources.ContextualVersionConflict: (torch 1.2.0 (/home/cmaurice/anaconda3/envs/open-mmlab/lib/python3.7/site-packages), Requirement.parse('torch&gt;=1.3'), {'mmdet'})
