### ISSUE TITLE
Difference between SKELETON_DATA.md and CUSTOM_DATASET.md

### ISSUE THREAD

**Issue by liqier** [open-mmlab/mmskeleton#336]
@yysijie ,hello, sorry to interrupt you, when I read the help documentation:
SKELETON_DATA.md and CUSTOM_DATASET.md are used to make data sets, can you tell me the difference and connection between SKELETON_DATA.md and CUSTOM_DATASET.md？

**Comment by AniketVelhankar** [comment]
@yysijie Yes, please explain this. I used the custom_dataset.md to generate JSON files. Now, should I use the kinetics_gendata.py  to build the database?
