### ISSUE TITLE
Annotation for the labels

### ISSUE THREAD

**Issue by BozhouZha** [open-mmlab/mmskeleton#347]
Hi there,

Thanks for sharing the amazing work! 

I'm trying to do some visualization job of the recognition part, just like the demo of original ST-GCN did. However, after attaining those labels, I wondered where I could find the annotation? 

I do noticed there is a file: _deprecated\origin_stgcn_repo\resource\kinetics_skeleton\label_name.txt_, and it looks like the annotation for the kinetics dataset but I'm not 100% sure. Could you please confirm that? Besides the kinetics, the annotation of NTU_RGB_D is also badly needed. I appreciate your help in advance!

**Comment by BozhouZha** [comment]
Solved, NVM

**Comment by zzz-afk** [comment]
> Solved, NVM

Do you know how to label a self-built dataset?

**Comment by yanghhx** [comment]
I have the same problem. Can you help me to solve it ?
