### ISSUE TITLE
how to understand person_id and id?

### ISSUE THREAD

**Issue by liqier** [open-mmlab/mmskeleton#353]
Hello,thanks for ST-GCN!
I want to create my own data set and learned that I need to convert the data into .json format and then into .pth format. 
I don’t understand the meaning of the parameters person_id and id through loader.py(\mmskeletonmaster\mmskeleton\datasets\skeleton\loader.py). 
![image](https://user-images.githubusercontent.com/55725190/88265614-6667e380-cd00-11ea-9d2c-387f7e5e4bb3.png)
Can you explain it?
Thank you very much!

**Comment by shelly-xue** [comment]
hi i meet the same problem with you,And i know 'id' is the number of person in every frame,the start id number is 0. Do you know the meaning of person_id? thank you very much!

**Comment by shelly-xue** [comment]
hi i meet the same problem with you,And i know 'id' is the number of person in every frame,the start id number is 0. Do you know the meaning of person_id? thank you very much! @liqier
