### ISSUE TITLE
help kinetics-skeleton.zip

### ISSUE THREAD

**Issue by liqier** [open-mmlab/mmskeleton#354]
The extracted skeleton data  called kinetics-skeleton(7.5GB) can be downloaded from GoogleDrive or BaiduYun, but BaiduYun resources cannot be viewed. Can you share them again?
Thank you very much

**Comment by xueyingliu** [comment]
@liqier Have you got the kinetics-skeleton(7.5GB) data?  I have the same problem.

**Comment by taoja12** [comment]
> @liqier Have you got the kinetics-skeleton(7.5GB) data? I have the same problem.

Have you got the data?kenetics-skeleton
