### ISSUE TITLE
mmskeleton using CUDA 11 on NVIDIA rtx 3080 GPU

### ISSUE THREAD

**Issue by lee-regina** [open-mmlab/mmskeleton#411]
Hello,

I'm quite new to machine learning and need to implement a motion recognition algorithm.
The lab computer that I need to use has 2 rtx 3080 GPUs.
Therefore, I will need to set-up mmskeleton with CUDA >11.0, and pytorch > 1.7.1
I tried setting mmskeleton up using the pytoch 1.7 versions of mmdetection and mmcv but it causes errors cause the newest mmskeleton version only works for older versions of mmdet and mmcv.
Has anyone been able to get mmskeleton working on rtx 3080/90?
Or, does anyone know how to update the mmskeleton code to work with the newest mmdetection and mmcv versions?

Thank you very much

**Comment by Noahhhhhhhhhhh** [comment]
> Hello,
> 
> I'm quite new to machine learning and need to implement a motion recognition algorithm.
> The lab computer that I need to use has 2 rtx 3080 GPUs.
> Therefore, I will need to set-up mmskeleton with CUDA >11.0, and pytorch > 1.7.1
> I tried setting mmskeleton up using the pytoch 1.7 versions of mmdetection and mmcv but it causes errors cause the newest mmskeleton version only works for older versions of mmdet and mmcv.
> Has anyone been able to get mmskeleton working on rtx 3080/90?
> Or, does anyone know how to update the mmskeleton code to work with the newest mmdetection and mmcv versions?
> 
> Thank you very much

Hi， @lee-regina ， I have the same question with you.Did you have solved it?

**Comment by lee-regina** [comment]
Hello @Noahhhhhhhhhhh 
I've managed to set-up mmskeleton using the pull request from @SebastienLinker 
The current setup used is with:
cuda 11.1
pytorch 1.8.1, torchvision 0.9.1
mmdet 1.12.0, mmcv 1.3.3

**Comment by pranavgundewar** [comment]
Hi @lee-regina - Did you git clone @SebastienLinker and then went ahead and installed all the latest requirements and dependencies?

Please let me know. Thank you.

**Comment by lee-regina** [comment]
> Hi @lee-regina - Did you git clone @SebastienLinker and then went ahead and installed all the latest requirements and dependencies?
> 
> Please let me know. Thank you.

Hello, 
As mentioned above, the setup I used is:
cuda 11.1
pytorch 1.8.1, torchvision 0.9.1
mmdet 1.12.0, mmcv 1.3.3

Also, I used python 3.9 for the conda environment
I'm not sure if it works with the latest mmdet and mmcv as I haven't tried it.

Regarding the other requirements in the requirement.txt file, I installed the latest version at the time, which were:
cython 0.29.23
pycocotools 2.0.2
lazy_import 0.2.2

Just extra information for those who may be stuck like I was, if you would like to install an older version of mmdet, go into the mmdetection github repository, go into releases, manually download the .zip of the version you want and follow their installation instructions.
