### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by Fanthers** [open-mmlab/mmskeleton#418]
my cuda version is 10.1, but pytorch do not have 1.2 version, so i install pytorch==1.4, but 
error: command '/usr/bin/nvcc' failed with exit status 1

**Comment by patasab** [comment]
> error: command '/usr/bin/nvcc' failed with exit status 1

Same error here, how did you solve it?

**Comment by Fanthers** [comment]
> > error: command '/usr/bin/nvcc' failed with exit status 1
> 
> Same error here, how did you solve it?

Sorry, this error has passed, I have forgotten how to modify it at that time, and I will not study this now, you can check other articles.
