### ISSUE TITLE
Creating a new classifier module to use custom dataset

### ISSUE THREAD

**Issue by lee-regina** [open-mmlab/mmskeleton#422]
Hello,

I'm trying to use ST-GCN on a custom dataset with 10 classes and a custom number of joints (i.e. 21 joints)
However, I get size mismatch errors when I use test.yaml after training the data.
According to issue #124 , I will need to create a new classifier module. 
Does anyone know which file I'd need to edit for this?

**Comment by lee-regina** [comment]
I think I solved it.
I just needed to specify the checkpoint to where the training model was saved to.
mmskl configs/recognition/st_gcn_aaai18/new_skeleton/test.yaml --checkpoint /work_dir/recognition/ST_GCN_18/ntu-rgbd-xsub/epoch_30.pth --gpus 1

**Comment by yuchen-ji** [comment]
> I think I solved it. I just needed to specify the checkpoint to where the training model was saved to. mmskl configs/recognition/st_gcn_aaai18/new_skeleton/test.yaml --checkpoint /work_dir/recognition/ST_GCN_18/ntu-rgbd-xsub/epoch_30.pth --gpus 1

Hello, I have similar problems with you.
I also want to use a custom skeleton-dataset to train the st gcn model, I have the following questions:
1）When the custom skeleton data is inconsistent with the openpose and kinect bone data supported by st-gcn, what adjustments should be made to the model?
2) I am going to use openpose to extract 2d bone data from the captured video. How many videos should be taken for each behavior category? And from what perspective？
I am a novice in this field, and I would appreciate your valuable advice!
