### ISSUE TITLE
problems with custom data building

### ISSUE THREAD

**Issue by liugd18** [open-mmlab/mmskeleton#424]
Hello, I'm trying using my own data to train this model.
I have a few videos in avi format which last around forty seconds, and I'm attempting using them to build data.
After writing annotation file and build-data-config file, I use
`mmskl configs/utils/fall.yaml --gpus 1`
but it doesn't work.
There is no error info. It seems that the code is still running but without progress. Besides, the gpu memory is being occupied by this but the util is 0%.
How can I solve this?

**Comment by WenLi-22** [comment]
hello,i also met the same question,have you solve it?if have ,can you tell how to solve it ?

**Comment by liugd18** [comment]
> hello,i also met the same question,have you solve it?if have ,can you tell how to solve it ?

sry, i failed to solve that. Instead, i replaced my data with mp4 format like the given example and it run smoothly.

**Comment by liugd18** [comment]
> hello,i also met the same question,have you solve it?if have ,can you tell how to solve it ?

Actually, there must be some way to solve this. If you do want to train with data in avi format, i guess you can check the process of building data. (I'm too lazy to do that and thus just use another dataset)

**Comment by linglingl635** [comment]
My data are all mp4 format, but I still face the same question. Did you have any other solutions?

**Comment by liugd18** [comment]
> My data are all mp4 format, but I still face the same question. Did you have any other solutions?

i feel sorry for not knowing that. i used this code on the pc of my internship company 2 years ago, thus not being able to solve this now. maybe opening a new issue would be helpful

**Comment by liugd18** [comment]
sorry for fogetting to close this issue. may all go smoothly
