### ISSUE TITLE
cannot import name 'download_url_to_file'_from 'torch.hub'

### ISSUE THREAD

**Issue by zzz-afk** [open-mmlab/mmskeleton#444]
When reproducing the mmskeleton model, I input the instruction Python mmskl py pose_ Demo, but the following error prompt occurs：

![QQ图片20220417165122](https://user-images.githubusercontent.com/93244409/163707760-46bc7903-8192-4ff4-98af-1a364b3ae459.jpg)

Ask for help.

**Comment by zzz-afk** [comment]
This problem has been solved.
as follows
![image](https://user-images.githubusercontent.com/93244409/163766118-3fe7dfe0-3b77-4ceb-8e26-c9b7963f0baa.png)

**Comment by jermycc** [comment]
您好，请问您完成复现了吗，可以加联系方式向您请教一些问题吗？qq1194963662，谢谢
