### ISSUE TITLE
Equation 6 from the ST-GCN paper

### ISSUE THREAD

**Issue by hshreeshail** [open-mmlab/mmskeleton#454]
This is in reference to the AAAI'18 paper "Spatial Temporal Graph Convolutional Networks for Skeleton-Based Action Recognition". In equation (6) of the paper, we have the conditional expression, d(v<sub>tj</sub>,v<sub>ti</sub>) <= K. Shouldn't it be d(v<sub>tj</sub>,v<sub>ti</sub>) <= D instead? Looks like a small type to me.
Do correct me if I am wrong.
Thanks.

**Comment by yjxiong** [comment]
Yes. I think you are correct here. Thanks for spotting the typo!

@yysijie
