### ISSUE TITLE
cannot test demo

### ISSUE THREAD

**Issue by taxuezcy** [open-mmlab/mmskeleton#54]
get the error :Can not find pose estimation results and the program exit @yysijie @yjxiong

**Comment by yjxiong** [comment]
I would suggest you post more context for others to help you.

**Comment by taxuezcy** [comment]
when run the demo ,the result is 
D:\ActionRecognition\st-gcn-master>python main.py demo --openpose D:\ActionRecognition\openpose\bin\OpenPoseDemo.exe --video D:/ActionRecognition/openpose/examples/media/video.avi
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\cuda\__init__.py:116: UserWarning:
    Found GPU0 GRID K1 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
The system cannot find the specified path。
Can not find pose estimation results.
@yjxiong 
could you help me to find the problem?  this trouble me for several days

**Comment by yysijie** [comment]
@taxuezcy, It seems that PyTorch doesn't support your GPU.
Now we have supported the training and inference on CPUs. Please update to the latest version and run:
`python main.py demo --use_gpu False --openpose <path to openpose build directory> [--video <path to your video> --device <gpu0> <gpu1>]`

**Comment by taxuezcy** [comment]
I have migrated to ubuntu and this problem is sloved, but new error happened when run the demo,
File "/home/cloud/st-gcn-master/processor/demo.py", line 49, in start
    output_snippets_dir, video_name, width, height)
  File "/home/cloud/st-gcn-master/tools/utils/openpose.py", line 17, in json_pack
    keypoints = person['pose_keypoints_2d']
KeyError: 'pose_keypoints_2d'
do you know the reason? @yysijie

**Comment by yysijie** [comment]
@taxuezcy, What's your Openpose version?

**Comment by yysijie** [comment]
@taxuezcy, the format of output json file by Openpose is unmatched. I think that they changed their format at the latest version. Could you move back to [62ad07](https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/62ad07)?

**Comment by taxuezcy** [comment]
I have found the reason ,the reason is the graphics card 's  compute capability is small, and I change another card ,now i can run the demo successfully,anyway,thank you very much @yysijie
