### ISSUE TITLE
'DataParallel' object has no attribute 'extract_feature' with demo

### ISSUE THREAD

**Issue by zhixiongzuo** [open-mmlab/mmskeleton#83]
Thanks for your work,
when i run the demo (cuda8,torch 0.4.1，cudnn6,1080Ti): 
sudo python main.py demo --openpose /media/madical201/405613A756139D2A/zzx/openpose-master/build --video ./clean_and_jerk.mp4 --device 0 1
i get this error:
  File "/media/madical201/405613A756139D2A/zzx/st-gcn-master/processor/demo.py", line 73, in start
    output, feature = self.model.extract_feature(data)
  File "/home/madical201/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'extract_feature'.
what should i do ?

**Comment by cloudlakecho** [comment]
The version change didn't work for me. I used Anaconda pytorch 0.4.0 and my solution was `self.model.extract_feature` -> ` self.model.module.extract_feature`
Reference: [fmassa](https://discuss.pytorch.org/t/how-to-reach-model-attributes-wrapped-by-nn-dataparallel/1373)

**Comment by xiaoxiongkubi** [comment]
sounds great, but I am not sure if it is the reason for anaconda. I did not install anaconda.

**Comment by lxy5513** [comment]
@cloudlakecho Thank you! I encounter same problem in Anaconda pytorch 0.4.0. 

you solution is work!  

After `self.model.extract_feature` -> ` self.model.module.extract_feature` . 

However  another problem occured ,
```
Visualization...
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/ssd/xyliu/projects/human_action_recognition/projects/st-gcn/processor/demo.py", line 85, in start
    edge = self.model.graph.edge
  File "/opt/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'graph'
```

same solution 
`edge = self.model.graph.edg -> edge = self.model.module.graph.edge`

It works.
